name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: afreydev/timeoff:${{ github.run_id }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set aws credentials
        run: |
          mkdir -p $HOME/.aws/
          echo ${{secrets.AWS_CREDENTIALS}} > $HOME/.aws/credentials
      - name: Create kube config
        run: |
          aws eks --region ${{secrets.AWS_REGION}} update-kubeconfig --name ${{secrets.AWS_CLUSTER_NAME}}
      - name: Deploy
        run: |
          helm upgrade --install --atomic timeoff ./helm/timeoff/ \
            --set image.tag=${{ github.run_id }}
